/****sql para los indicadores */
select VIEW_NAME,TEXT_VC from ALL_VIEWS where view_name like 'VTA_VERTI%'


(	SELECT EJERCICIO, MES AS MES,UEN,T1.CODIGO_ARTICULO, T1.ARTICULO_NOMBRE, T1.REG, COUNT(T1.CLIENTE_ID) AS CANT_CLIENTES, SUM(T1.				CANTIDAD_UNIT) AS CANTIDAD_UNIT, sum(T1.IMPORTE_FACTURADO) AS BS_IMPORTE_FACTURADO, (SELECT COUNT(NOMBRE) AS CANTIDAD_CLIENTES FROM 	(SELECT decode(CLIENTES.ZONA,'0410','SCZ','0420','LPZ','0430','CBBA','0440','TJA','0450','ALTO','0451','ALTO','0460','SCR','0461',		'SCR','0470','BENI','0471','BENI','SIN REG') REG, CLIENTES.*
	FROM CLIENTES WHERE CODIGO_EMPRESA='004' AND FECHA_BAJA IS NULL) T2 WHERE T2.REG= T1.REG GROUP BY REG) AS CANTIDAD_CLIENTES_REG
	FROM (SELECT EJERCICIO, V_MES AS MES, CODIGO_ARTICULO, ARTICULO_NOMBRE, CLIENTE_ID, CLIENTE_NOMBRE,UEN, REG, SUM(CANTIDAD) AS CANTIDAD_UNIT, SUM(IMP_FACTURADO) AS IMPORTE_FACTURADO fROM BOL_BI_VTAS_PPTO WHERE CANTIDAD>0 GROUP BY EJERCICIO,V_MES,CODIGO_ARTICULO, ARTICULO_NOMBRE,CLIENTE_ID,CLIENTE_NOMBRE,UEN, REG)  T1
	GROUP BY EJERCICIO, MES,UEN,T1.CODIGO_ARTICULO, T1.ARTICULO_NOMBRE, T1.REG
)


/* ************* */
REGION | UEN | # clientes ttl | # Clie Visitado | # venta realizada a clie | # articulos vendidos | unidades vendidas | valor de la venta | promedio vta 6 meses UN|

SELECT EJERCICIO, V_MES AS MES, CODIGO_ARTICULO, ARTICULO_NOMBRE, CLIENTE_ID, CLIENTE_NOMBRE,UEN, REG, SUM(CANTIDAD) AS CANTIDAD_UNIT, SUM(IMP_FACTURADO) AS IMPORTE_FACTURADO fROM BOL_BI_VTAS_PPTO WHERE CANTIDAD>0 GROUP BY EJERCICIO,V_MES,CODIGO_ARTICULO, ARTICULO_NOMBRE,CLIENTE_ID,CLIENTE_NOMBRE,UEN, REG)

/** lista general de las ventas*****/
select ejercicio,v_mes,uen,reg,subreg,CLIENTE_ID,cliente_nombre,0 nro_clie_visitado,0 nro_vta_real ,cantidad,IMP_NETO,IMP_FACTURADO,0 prom_un_6m fROM BOL_BI_VTAS_PPTO WHERE CANTIDAD>0 and EJERCICIO='2021' and v_mes=02
/***** select **/

select ejercicio,v_mes,uen,reg,subreg,CLIENTE_ID,cliente_nombre, nombre_agente,sum(0) nro_clie_visitado,sum(0) nro_vta_real ,sum(cantidad) un,sum(IMP_NETO) bs_neto,sum(IMP_FACTURADO) bs_fact,sum(0) prom_un_6m FROM BOL_BI_VTAS_PPTO WHERE CANTIDAD>0 and EJERCICIO='2021' and v_mes=02
GROUP BY EJERCICIO, v_MES,UEN,reg,subreg,CLIENTE_ID,cliente_nombre,nombre_agente

select * fROM BOL_BI_VTAS_PPTO WHERE CANTIDAD>0 and EJERCICIO='2021' and v_mes=02